### ISSUE TITLE
Allow SourceLocation properties

### ISSUE THREAD

**Issue by couchand** [shapesecurity/shift-ast-js#36]
Though #19 added SourceLocation constructors, it didn't actually introduce the ability to use them anywhere.  In particular, they are explicitly removed here: https://github.com/shapesecurity/shift-ast-js/blob/9bacd51983c2a0217d4430995588744a9d7be6e8/src/generate.js#L56

It seems like all that is needed is to remove this removal.  Is there any objection to doing so?

**Comment by michaelficarra** [comment]
Yeah, since https://github.com/shapesecurity/shift-java/pull/101, we've decided the way we'd like to handle ad-hoc information collected at parse time is to allow subclasses of the parser to store state in a side table in the parser instance. That means we'll be removing the `loc` property from AST nodes (and, more importantly, not gating new state on updates to the AST format).

**Comment by couchand** [comment]
Does this mean there will be no way to generate source maps directly from an AST?  It seems like it would be natural to have `shift-codegen` have an option to generate source maps, in the way that `escodegen` does.  Now it looks like the preferred way to implement that would be to pass in a codegen class that itself has a reference to the side table and then builds up the source map on the side.  Does that sound right?

**Comment by michaelficarra** [comment]
That sounds right. For shift-codegen to generate a source map, it would need to be passed both the AST and the side table extracted from ParserWithLocation. If we wanted to keep the side table format completely internal, shift-codegen could also be passed the ParserWithLocation instance itself, as long as ParserWithLocation has a sufficient API.

**Comment by michaelficarra** [comment]
Closing, as nothing needs to be done in this repo. Locations will not be tracked in the AST.
